// Generated by CoffeeScript 2.5.1
(function() {
  var app, attachSCIFunctions, bodyParser, express, listenForRequests, port, routes;

  Object.defineProperty(exports, "__esModule", {
    value: true
  });

  //###########################################################
  require('systemd');

  express = require('express');

  bodyParser = require('body-parser');

  //###########################################################
  //region internalProperties
  routes = null;

  port = null;

  //###########################################################
  app = express();

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(bodyParser.json());

  //endregion

  //###########################################################
  attachSCIFunctions = function() {
    var fun, route;
    for (route in routes) {
      fun = routes[route];
      app.post("/" + route, fun);
    }
  };

  //################################################################
  listenForRequests = function() {
    if (process.env.SOCKETMODE) {
      app.listen("systemd");
    } else {
      app.listen(port);
    }
  };

  //###########################################################
  exports.prepareAndExpose = function(leRoutes, lePort = 3333) {
    if (typeof leRoutes !== "object") {
      throw new Error("No routes Object provided!");
    }
    routes = leRoutes;
    port = process.env.PORT || lePort;
    attachSCIFunctions();
    listenForRequests();
  };

}).call(this);
